# Generated by Django 3.2 on 2023-05-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pifuvueweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='img_name',
            field=models.CharField(default=' ', max_length=1000),
        ),
    ]
